# Generated by Django 5.1.4 on 2025-01-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_friendly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
